server:
  port: 8880

spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
  mvc:
    hidden-method:
      filter:
        enabled: true

  #  database setting
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:beacon
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # jpa setting
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # dev tools
  devtools:
    livereload:
      enabled: true

  # ThymeleafProperties
  thymeleaf:
    cache: false # 운영에서는 true

logging:
  level:
    root: info # debug